-- REGEXP 이용해서 다수의 문자열 추출하기
-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS 
  FROM CAR_RENTAL_COMPANY_CAR
 WHERE OPTIONS REGEXP "통풍시트|열선시트|가죽시트"
 GROUP BY CAR_TYPE
 ORDER BY CAR_TYPE

-- AS ""했을 때는  재정의한 이름으로 ORDER BY... 에서 사용하지 말것
-- 진료과별 총 예약 횟수 출력하기
SELECT MCDP_CD AS "진료과코드", COUNT(PT_NO) AS "5월예약건수"
  FROM APPOINTMENT
 WHERE DATE_FORMAT(APNT_YMD,"%Y-%m")="2022-05"
 GROUP BY MCDP_CD
 ORDER BY COUNT(PT_NO) ASC, MCDP_CD ASC

-- 입양 시각 구하기(1)
SELECT HOUR(DATETIME), COUNT(ANIMAL_ID)
  FROM ANIMAL_OUTS
 WHERE HOUR(DATETIME)>=9 AND HOUR(DATETIME)<20
 GROUP BY HOUR(DATETIME)
 ORDER BY HOUR(DATETIME)

-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT MONTH(START_DATE) AS MONTH
     , CC.CAR_ID
     , COUNT(*) AS "RECORDS"
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CC
  JOIN (
        SELECT CAR_ID
             , COUNT(*) AS CNT
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE YEAR(START_DATE)=2022 AND MONTH(START_DATE) IN (8,9,10)
         GROUP BY CAR_ID
  ) SUB
    ON SUB.CAR_ID=CC.CAR_ID
 WHERE SUB.CNT >= 5 
       AND YEAR(START_DATE)=2022 AND MONTH(START_DATE) IN (8,9,10)
 GROUP BY MONTH(START_DATE), CAR_ID
 ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC

-- SUM
 -- 카테고리 별 도서 판매량 집계하기
SELECT B.CATEGORY, SUM(BSY.SALES) AS TOTAL_SALES
  FROM BOOK B
  JOIN (SELECT *
  FROM BOOK_SALES BS
 WHERE DATE_FORMAT(SALES_DATE,"%Y-%m")="2022-01") BSY
    ON B.BOOK_ID=BSY.BOOK_ID
 GROUP BY B.CATEGORY
 ORDER BY B.CATEGORY ASC

 -- 카테고리 별 도서 판매량 집계하기
SELECT B.CATEGORY, SUM(BSY.SALES) AS TOTAL_SALES
  FROM BOOK B
  JOIN (SELECT *
  FROM BOOK_SALES BS
 WHERE DATE_FORMAT(SALES_DATE,"%Y-%m")="2022-01") BSY
    ON B.BOOK_ID=BSY.BOOK_ID
 GROUP BY B.CATEGORY
 ORDER BY B.CATEGORY ASC