-- DATE format 확인해야함!
-- 조건에 맞는 도서와 저자 리스트 출력하기
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
  FROM BOOK 
  JOIN AUTHOR
    ON BOOK.AUTHOR_ID=AUTHOR.AUTHOR_ID 
 WHERE BOOK.CATEGORY="경제"
 ORDER BY BOOK.PUBLISHED_DATE

 -- 상품 별 오프라인 매출 구하기
SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) AS SALES
  FROM PRODUCT AS P, OFFLINE_SALE AS OS
 WHERE P.PRODUCT_ID=OS.PRODUCT_ID
 GROUP BY PRODUCT_CODE
 ORDER BY SALES DESC, PRODUCT_CODE