-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
  FROM ANIMAL_INS
 WHERE animal_type='Dog' AND lower(NAME) LIKE lower('%el%')
 ORDER BY NAME

 -- 아픈 동물 찾기
SELECT ANIMAL_ID, NAME
  FROM ANIMAL_INS
 WHERE INTAKE_CONDITION='Sick'
ORDER BY ANIMAL_ID

-- 어린 동물 찾기
SELECT ANIMAL_ID, NAME
  FROM ANIMAL_INS
 WHERE INTAKE_CONDITION!='Aged'
ORDER BY ANIMAL_ID

-- 상위 n개 레코드
SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 조건에 맞는 회원수 구하기
SELECT COUNT(*) 
  FROM USER_INFO
 WHERE YEAR(JOINED)="2021"
   AND AGE BETWEEN 20 AND 29

-- 가장 비싼 상품 구하기
SELECT MAX(PRICE) AS MAX_PRICE
  FROM PRODUCT

-- 최댓값 구하기
SELECT MAX(DATETIME) AS 시간
  FROM ANIMAL_INS

-- 최솟값 구하기
SELECT DATETIME
 FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 동물 수 구하기
SELECT count(ANIMAL_ID) 
  FROM ANIMAL_INS

-- 중복 제거하기
SELECT count(DISTINCT NAME)
  FROM ANIMAL_INS
WHERE NAME IS NOT NULL

-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(F.TOTAL_ORDER)
  FROM FIRST_HALF AS F
INNER JOIN ICECREAM_INFO AS II 
        ON F.FLAVOR= II.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC

-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE)
  FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
HAVING ANIMAL_TYPE='Cat' OR ANIMAL_TYPE='Dog'
ORDER BY ANIMAL_TYPE

-- 동명 동물 수 찾기
SELECT * 
FROM (SELECT NAME, COUNT(NAME) AS COUNT
        FROM ANIMAL_INS
       WHERE NAME IS NOT NULL
    GROUP BY NAME
    ORDER BY NAME)  A
WHERE COUNT > 1 

-- 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT YEAR(O.SALES_DATE) AS YEAR
     , MONTH(O.SALES_DATE) AS MONTH
     , U.GENDER AS GENDER
     , COUNT(DISTINCT O.USER_ID) AS USERS
  FROM USER_INFO U, ONLINE_SALE O
 WHERE U.USER_ID = O.USER_ID
    AND GENDER IS NOT NULL
 GROUP BY YEAR, MONTH, GENDER
 ORDER BY YEAR, MONTH, GENDER
