-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
  FROM ANIMAL_INS
 WHERE animal_type='Dog' AND lower(NAME) LIKE lower('%el%')
 ORDER BY NAME

 -- 아픈 동물 찾기
SELECT ANIMAL_ID, NAME
  FROM ANIMAL_INS
 WHERE INTAKE_CONDITION='Sick'
ORDER BY ANIMAL_ID

-- 어린 동물 찾기
SELECT ANIMAL_ID, NAME
  FROM ANIMAL_INS
 WHERE INTAKE_CONDITION!='Aged'
ORDER BY ANIMAL_ID

-- 상위 n개 레코드
SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 조건에 맞는 회원수 구하기
SELECT COUNT(*) 
  FROM USER_INFO
 WHERE YEAR(JOINED)="2021"
   AND AGE BETWEEN 20 AND 29

-- 가장 비싼 상품 구하기
SELECT MAX(PRICE) AS MAX_PRICE
  FROM PRODUCT

-- 최댓값 구하기
SELECT MAX(DATETIME) AS 시간
  FROM ANIMAL_INS

-- 최솟값 구하기
SELECT DATETIME
 FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1