-- SUBSTRING 을 이용해서 원하는 만큼 데이터를 추출할 수 있었다
-- 카테고리 별 상품 개수 구하기
SELECT SUBSTRING(PRODUCT_CODE,1,2) AS CATERGORY, COUNT(PRODUCT_ID) AS PRODUCTS
  FROM PRODUCT
 GROUP BY CATERGORY
 ORDER BY CATERGORY

-- 결과의 데이터 포맷에 따라서 추출
 -- DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME,"%Y-%m-%d")
  FROM ANIMAL_INS
 ORDER BY ANIMAL_ID